infisical_containers:
  - project: portainer-prod-3
    path: /portainer-prod-3
    env: prod
  - project: checkmk-prod-1
    path: /checkmk-prod-1
    env: prod
  - project: newt-prod-1
    path: /newt-prod-1
    env: prod
  - project: traefik-prod-3
    path: /traefik-prod-3
    env: prod
  - project: n8n-prod-1
    path: /n8n-prod-1
    env: prod
  - project: linkwarden-prod-1
    path: /linkwarden-prod-1
    env: prod
  - project: loki-prod-4
    path: /loki-prod-4
    env: prod
  - project: stirlingpdf-prod-1        # typo in the actual compose label - see note below
    path: /stirlingpdf-prod-1
    env: prod
  - project: scanopy-prod-1
    path: /scanopy-prod-1
    env: prod
  - project: crowdsec-prod-3
    path: /crowdsec-prod-3
    env: prod
  - project: semaphore-prod-1
    path: /semaphore-prod-1
    env: prod
  - project: dockhand-prod-1
    path: /dockhand-prod-1
    env: prod
  - project: it-tools-prod-1
    path: /it-tools-prod-1
    env: prod
  - project: atlas-prod-1
    path: /atlas-prod-1
    env: prod
  - project: infisical-prod-1
    path: /infisical-prod-1
    env: prod

#added for dockhand secret builds.....
dockhand_owner: "semaphore"   # e.g. dockhand, or a UID-based service account
dockhand_group: "repogroup"
dockhand_writer: true
# dockhand_containers: "{{ infisical_containers }}"   # now its all.yml group_vars to include all containers from all hosts, not just this host.  This is so we can build all .env files for all dockhand stacks on cyborg in one run of the playbook.
# if we need it different then all currently managed containers
# dockhand_containers:
#   - project: paperless-prod-1
#     env: prod
#     path: /paperless
#   - project: linkwarden-prod-1
#     env: prod
#     path: /linkwarden
#   # ...one entry per dockhand-managed stack on cyborg