infisical_containers:
  - project: traefik-prod-4
    path: /traefik-prod-4
    env: prod
  - project: crowdsec-prod-4
    path: /crowdsec-prod-4
    env: prod
  - project: autoheal-prod-1
    path: /autoheal-prod-1
    env: prod
  - project: paperless-prod-1
    path: /paperless-prod-1
    env: prod
  - project: navidrome-prod-1
    path: /navidrome-prod-1
    env: prod
  - project: immich-prod-1
    path: /immich-prod-1
    env: prod