# Make sure Ansible host has access to these devices
# Good idea to snapshot all machines and deploy uing cloud-init

[servers]
server1 ansible_host=192.168.1.239
server2 ansible_host=192.168.1.236
server3 ansible_host=192.168.1.169


[agents]
agent1 ansible_host=192.168.1.218
agent2 ansible_host=192.168.1.227
agent3 ansible_host=192.168.1.173
agent4 ansible_host=192.168.1.208

[rke2]

[rke2:children]
servers
agents

[rke2:vars]
ansible_user=semaphore
