---
automation_user: mkane
automation_secret: Damnskippy10!
server_url: https://checkmk.local.kaneworld.org
site: KaneCo
#checkmk_server: "checkmk.local.kaneworld.org" 
checkmk_server: cyborg.kane.mk
checkmk_version: 2.4.0p8
checkmk_edition: cre
checkmk_protocol: https
#scriptinventory: pihole3.kane.mk