# vars/repo_targets.yml
# Define repos and which servers each should be pushed to

#nas_base_path: /share/CACHEDEV1_DATA/Public/Documents/SourceControl   # Path on QNAP NAS where repos live
#repo_base_path: /home/murry/repos                                     # Local path on cyborg where repos will be pulled from NAS before pushing to servers
#dest_base_path: /home/murry/repos                                     # Destination path on target servers
repo_base_path: /opt/repos                                     # Local path on cyborg where repos will be pulled from NAS before pushing to servers
dest_base_path: /opt/repos                                     # Destination path on target servers

repos:
  - name: ansible
    src: "{{ repo_base_path }}/Ansible"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk

  - name: homelab
    src: "{{ repo_base_path }}/HomeLab"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk

  - name: scripts
    src: "{{ repo_base_path }}/scripts"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk

  - name: terraform
    src: "{{ repo_base_path }}/terraform"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk

