# vars/repo_targets.yml
# Define repos and which servers each should be pushed to

#nas_base_path: /share/CACHEDEV1_DATA/Public/Documents/SourceControl   # Path on QNAP NAS where repos live
#repo_base_path: /home/murry/repos                                     # Local path on cyborg where repos will be pulled from NAS before pushing to servers
#dest_base_path: /home/murry/repos                                     # Destination path on target servers
repo_base_path: /opt/repos                                     # Local path on cyborg where repos will be pulled from NAS before pushing to servers
dest_base_path: /opt/repos                                     # Destination path on target servers
unraid_base_path: /mnt/user/data/sourcecontrol 

repos:
  - name: ansible
    src: "{{ repo_base_path }}/ansible"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk
      - auth.kane.mk
      - docker-ceph.kane.mk
      - docker-dev.kane.mk
      - cyborg.kane.mk

  - name: homelab
    src: "{{ repo_base_path }}/homelab"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk
      - auth.kane.mk
      - docker-ceph.kane.mk
      - docker-dev.kane.mk
      - cyborg.kane.mk

  - name: scripts
    src: "{{ repo_base_path }}/scripts"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk
      - auth.kane.mk
      - docker-ceph.kane.mk
      - docker-dev.kane.mk
      - cyborg.kane.mk

  - name: terraform
    src: "{{ repo_base_path }}/terraform"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk
      - auth.kane.mk
      - docker-ceph.kane.mk
      - docker-dev.kane.mk
      - cyborg.kane.mk

  - name: kaneworld
    src: "{{ repo_base_path }}/kaneworld"
    targets:
      - mkserver.kane.mk
      - raptor.kane.mk
      - stargate.kane.mk
      - auth.kane.mk
      - docker-ceph.kane.mk
      - docker-dev.kane.mk
      - cyborg.kane.mk
