[ubuntu]
minidocker.kane.mk
minijellyfin.kane.mk
mkserver.kane.mk

[unraid]
kaneserver.kane.mk

[prox]
proxmini.kane.mk

[desktop]
murdogpc.kane.mk

[ubuntu:vars]
ansible_ssh_user=root
#ansible_ssh_pass=nononono
ansible_ssh_private_key_file=~/.ssh/id_rsa

[unraid:vars]
ansible_ssh_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa

[prox:vars]
ansible_ssh_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa

[desktop:vars]
ansible_user=MurryKane
ansible_password=Skippy10!
ansible_connection=winrm
ansible_winrm_transport=basic