all:
  children:
    pbs_servers:
      hosts:
        pbs.kane.mk:
        pbs-mini.kane.mk:
    lxc: 
      hosts:
        dns-primary.kane.mk: 
        dns-secondary.kane.mk:
    ubuntu:
      hosts:
        mkserver.kane.mk:
        authentik.kane.mk:
          ansible_python_interpreter: /usr/bin/python3.11
        cyborg.kane.mk:
        pbs.kane.mk:
        pbs-mini.kane.mk:
        #utilserver.kane.mk:
        raptor.kane.mk:
        unifi.kane.mk:
        stargate.kane.mk:
        dns-primary.kane.mk:
        dns-secondary.kane.mk:
        netbird.kane.mk:
        auth.kane.mk:
      vars:
        #ansible_python_interpreter: auto_silent
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: root
        ansible_become: true 
        ansible_become_method: sudo
    prox:
      hosts:
        coco.kane.mk:
        mini.kane.mk:
        apex.kane.mk:
        athena.kane.mk:
      vars:
        ansible_python_interpreter: auto_silent
        ansible_user: root
        ansible_become: true
        ansible_become_method: sudo
    windows:
      hosts:
        murdogpc.kane.mk: 
      vars:
        ansible_user: ansible
        ansible_password: Skippy10!
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        ansible_python_interpreter: C:\Users\MurDog\AppData\Local\Programs\Python\python312
    unraid:
      hosts:
        kaneserver.kane.mk: 
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
    qnap:
      hosts:
        murdognas.kane.mk: 
      vars:
        ansible_port: 8622
        ansible_user: MurryKane
        ansible_become_user: admin
        ansible_python_interpreter: /share/CACHEDEV1_DATA/.qpkg/Python3/opt/python3/bin/python3  
    docker:
      hosts:
        mkserver.kane.mk: 
        #utilserver.kane.mk:
        cyborg.kane.mk:
        auth.kane.mk:
        raptor.kane.mk:
        netbird.kane.mk:
        murdognas.kane.mk:
      vars:
        docker_allowed_subnets:
          - 192.168.1.0/24
          - 10.0.0.0/8
        docker_tls_san:
          - "IP:{{ ansible_default_ipv4.address }}"
          - "IP:127.0.0.1"
          - "DNS: {{ inventory_hostname}}"
          - "DNS: {{ inventory_hostname}}.kane.mk"
          - "DNS:192.168.1.215"
          - "DNS:192.168.1.219"
          - "DNS:192.168.1.4"
    unifi:
      hosts:
        unifi.kane.mk:
      vars:
        #ansible_python_interpreter: auto_silent
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: root
        ansible_become: true 
        ansible_become_method: sudo
