- name: Install HAProxy and Keepalived
  apt:
    name:
      - haproxy
      - keepalived
    state: present
    update_cache: yes

- name: Deploy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart HAProxy

- name: Deploy Keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart Keepalived

- name: Ensure HAProxy is running and enabled
  service:
    name: haproxy
    enabled: yes
    state: started

- name: Ensure Keepalived is running and enabled
  service:
    name: keepalived
    enabled: yes
    state: started
