# ==============================
# roles/alloy/tasks/install.yml
# ==============================
- name: Ensure alloy user exists
  user:
    name: "{{ alloy_user }}"
    system: yes
    create_home: no

- name: Add alloy to docker group
  user:
    name: "{{ alloy_user }}"
    groups: docker
    append: yes
  when: alloy_has_docker

- name: Gather service facts
  service_facts:

- name: Define node exporter service names
  set_fact:
    node_exporter_services:
      - node_exporter.service
      - prometheus-node-exporter.service
      - node-exporter.service

- name: Find installed node exporter services
  set_fact:
    found_node_exporters: "{{ node_exporter_services | select('in', ansible_facts.services) | list }}"

- name: Stop node exporter services
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ found_node_exporters }}"

- name: Disable node exporter services
  service:
    name: "{{ item }}"
    enabled: no
  loop: "{{ found_node_exporters }}"

- name: Stop node exporter timers
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - prometheus-node-exporter-apt.timer
    - prometheus-node-exporter-nvme.timer
    - prometheus-node-exporter-smartmon.timer
  when: item in ansible_facts.services

# - name: Remove node_exporter if present
#   block:
#     - name: Stop node_exporter
#       service:
#         name: node_exporter
#         state: stopped
#       ignore_errors: true

#     - name: Disable node_exporter
#       service:
#         name: node_exporter
#         enabled: no
#       ignore_errors: true

- name: Install Alloy
  ansible.builtin.include_role:
    name: grafana.grafana.alloy
  vars:
    alloy_config: |
      prometheus.scrape "default" {
        targets = [{"__address__" = "localhost:12345"}]
        forward_to = [prometheus.remote_write.default.receiver]
      }
      prometheus.remote_write "default" {
        endpoint {
            url = "http://mkserver.kane.mk:9090/api/v1/write"
        }
      }


- name: Allow for custom log directory source
  ansible.builtin.template:
    src: default_alloy.j2
    #dest: /etc/default/config.alloy
    dest: "{{ alloy_default_conf }}"
    owner: root
    group: root
    mode: '0644'

- name: Config File is set for directory mode and not file mode
  ansible.builtin.lineinfile:
    path: "{{ alloy_base_env }}"
    regexp: '^CONFIG_FILE='
    line: CONFIG_FILE="/opt/alloy"
  notify: Restart alloy

- name: Config File is set for directory mode and not file mode
  ansible.builtin.lineinfile:
    path: "{{ alloy_base_env }}"
    regexp: '^CUSTOM_ARGS='
    line: CUSTOM_ARGS="--server.http.listen-addr=0.0.0.0:12345"
  notify: Restart alloy

- name: Config File is set for directory mode and not file mode
  ansible.builtin.lineinfile:
    path: "{{ alloy_base_env }}"
    regexp: '^RESTART_ON_UPGRADE='
    line: RESTART_ON_UPGRADE=true
  notify: Restart alloy

- name: Replace Config file for Alloy
  ansible.builtin.template:
    src: default_alloy.j2
    #dest: /etc/alloy/config.alloy
    dest: "{{ alloy_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart alloy


# - name: Allow Alloy UI from LAN
#   community.general.ufw:
#     rule: allow
#     port: "12345"
#     proto: tcp
#     src: 192.168.1.0/24
