# ==============================
# roles/alloy/tasks/restart.yml
# ==============================
- name: Ensure alloy service is running
  service:
    name: "{{ alloy_service_name }}"
    state: restarted
    enabled: true
  when: ansible_facts['system'] != "Win32NT"

- name: Restart alloy on Windows
  win_service:
    name: alloy
    state: restarted
  when: ansible_facts['system'] == "Win32NT"