# - name: Configure docker daemon
#   copy:
#     dest: /etc/docker/daemon.json
#     content: |
#       {
#         "hosts": ["tcp://0.0.0.0:{{ docker_tls_port }}", "unix:///var/run/docker.sock"],
#         "tls": true,
#         "tlscacert": "{{ docker_tls_dir }}/ca.pem",
#         "tlscert": "{{ docker_tls_dir }}/server-cert.pem",
#         "tlskey": "{{ docker_tls_dir }}/server-key.pem",
#         "tlsverify": true
#       }
#   notify: restart docker

- name: Deploy Docker daemon config
  template:
    src: daemon.json  
    #est: "{{ alloy_config_dir }}/{{ item | regex_replace('.j2$', '') }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  #notify: restart docker
  when: ansible_facts.system == "Linux"

- name: Create systemd override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0700'  
    owner: root
    group: root
  when: ansible_facts.system == "Linux"

# - name: Deploy Docker daemon config
#   template:
#     src: override.conf
#     #dest: "{{ alloy_config_dir }}/{{ item | regex_replace('.j2$', '') }}"
#     dest: /etc/systemd/system/docker.service.d/override.conf
#     owner: root
#     group: root
#     mode: '0644'
#   notify:
#     - reload systemd
#     - restart docker
#   when: ansible_facts.system == "Linux"

- name: Deploy docker systemd override (TLS)
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: '0644'
    owner: root
    group: root
  when: ansible_facts.system == "Linux"
  notify:
    - reload systemd
    - restart docker

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
