[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2376 --containerd=/run/containerd/containerd.sock --tlsverify --tlscacert=/home/murry/certs/ca.pem  --tlscert=/home/murry/certs/cert.pem --tlskey=/home/murry/certs/key.pem
Environment=DOCKER_MIN_API_VERSION=1.24
