---
records:
  - zone: local.kaneworld.org
    name: mini
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: router
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: unraid
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: influxdb
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: prometheus
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: arris
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: nas
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: qvr
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: kemp
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: ansible
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: unifi
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: monitoring
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: homepage
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: speedtest
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: sonarr
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: radarr
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: prowlarr
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: qbittorrent
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: homeassist
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: nas-portainer
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: vaultwarden
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: bazarr
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: nextcloud
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: jellyseerr
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: ups
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: nodered
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: hahome
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: bosmox
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: tdarr
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: coco
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: minijellyfin
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: fileflow
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: authentik
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: pbs
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: cadvisor-unraid
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: slzb-06
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: semaphore
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: mini-portainer
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik-prod-2
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: cadvisor-prod-2
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: fileflows-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: jellyseerr-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: krusader-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: node_exporter-prod-2
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: portainer-prod-2
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: promtail-prod-2
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: prowlarr-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: qbittorrent-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: radarr-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: recyclarr-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: sonarr-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik-prod-3
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: portainer-prod-3
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: semaphore-prod-1
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: traefik-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: portainer-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: homepage-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: kuma-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: unifi-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: vaultwarden-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: cadvisor-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik3-widget
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: traefik1-widget
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik2-widget
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: alertmanager
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: checkmk
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: semaphore-api
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: loki-prod-4
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: huntarr-prod-1
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik1-metrics
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik2-metrics
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik3-metrics
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: monitoring-widget
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: it-tools
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: nvidia
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: n8n
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: gotify
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: stirlingpdf
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: linkwarden
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: jellyfin
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: tinymedia
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: filebot
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: apprise
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: dns-primary
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: dns-secondary
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: dns-tertiary
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: fileflows
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: athena
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: apex
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: dockhand
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: atlas
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: pbs-mini
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: qui-prod-1
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik-prod-4
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: traefik4-widget
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: traefik4-metrics
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: dozzle-prod-4
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: paperless
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: paperless-ai
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: paperless-gbt
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: open-webui
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: immich
    ip: raptor.kane.mk
  - zone: local.kaneworld.org
    name: dozzle-prod-1
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: dozzle-prod-2
    ip: utilserver.kane.mk
  - zone: local.kaneworld.org
    name: dozzle-prod-3
    ip: cyborg.kane.mk
  - zone: local.kaneworld.org
    name: dozzle-prod-5
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik-prod-5
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: sonarr-prod-2
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: radarr-prod-2
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: qbittorrent-prod-2
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: cleanuparr-prod-1
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: huntarr-prod-2
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: jellyseerr-prod-2
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: krusader-prod-2
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: prowlarr-prod-2
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: portainer-prod-5
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: netbird
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: auth
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: portainer-prod-6
    ip: mkserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik-prod-6
    ip: auth.kane.mk
  - zone: local.kaneworld.org
    name: traefik6-widget
    ip: auth.kane.mk
  - zone: local.kaneworld.org
    name: traefik6-metrics
    ip: auth.kane.mk
  - zone: local.kaneworld.org
    name: traefik5-widget
    ip: kaneserver.kane.mk
  - zone: local.kaneworld.org
    name: traefik5-metrics
    ip: kaneserver.kane.mk