---
records:
  - zone: kane.mk
    name: mkserver
    ip: 192.168.1.234
  - zone: kane.mk
    name: murdogap
    ip: 192.168.1.170
  - zone: kane.mk
    name: uswfmtv1
    ip: 192.168.107.57
  - zone: kane.mk
    name: uswfmtv2
    ip: 192.168.107.58
  - zone: kane.mk
    name: murpad
    ip: 192.168.1.111
  - zone: kane.mk
    name: adrianasmac
    ip: 192.168.1.197
  - zone: kane.mk
    name: adrianamac
    ip: 192.168.1.187
  - zone: kane.mk
    name: adrianasphone
    ip: 192.168.1.205
  - zone: kane.mk
    name: aliciasipad
    ip: 192.168.1.130
  - zone: kane.mk
    name: aliciasiphone
    ip: 192.168.1.98
  - zone: kane.mk
    name: aliciasmac
    ip: 192.168.1.197
  - zone: kane.mk
    name: aliciaspc
    ip: 192.168.1.217
  - zone: kane.mk
    name: amazonfirecube
    ip: 192.168.107.53
  - zone: kane.mk
    name: amazonfireoffice
    ip: 192.168.107.75
  - zone: kane.mk
    name: amazongarage
    ip: 192.168.107.72
  - zone: kane.mk
    name: amazonhallway
    ip: 192.168.107.44
  - zone: kane.mk
    name: amazonkitchen
    ip: 192.168.107.86
  - zone: kane.mk
    name: amazonmaster
    ip: 192.168.107.32
  - zone: kane.mk
    name: amazonoffice
    ip: 192.168.107.31
  - zone: kane.mk
    name: amazonpatio
    ip: 192.168.107.40
  - zone: kane.mk
    name: amazonplugoffice
    ip: 192.168.107.36
  - zone: kane.mk
    name: applemini
    ip: 192.168.1.226
  - zone: kane.mk
    name: appletv
    ip: 192.168.107.61
  - zone: kane.mk
    name: brendensphone
    ip: 192.168.1.101
  - zone: kane.mk
    name: camerabackyard
    ip: 192.168.1.135
  - zone: kane.mk
    name: cameradoorbell
    ip: 192.168.1.154
  - zone: kane.mk
    name: camerafront
    ip: 192.168.1.70
  - zone: kane.mk
    name: cameragarage
    ip: 192.168.1.64
  - zone: kane.mk
    name: cameragate
    ip: 192.168.1.137
  - zone: kane.mk
    name: camerapatio
    ip: 192.168.1.192
  - zone: kane.mk
    name: fileflow
    ip: 192.168.1.113
  - zone: kane.mk
    name: flumemurdog
    ip: 192.168.107.33
  - zone: kane.mk
    name: goveefense1
    ip: 192.168.107.82
  - zone: kane.mk
    name: goveefense2
    ip: 192.168.107.83
  - zone: kane.mk
    name: goveegazebo
    ip: 192.168.107.85
  - zone: kane.mk
    name: goveespare
    ip: 192.168.107.84
  - zone: kane.mk
    name: hahome
    ip: 192.168.1.209
  - zone: kane.mk
    name: hp8715
    ip: 192.168.1.102
  - zone: kane.mk
    name: homepage
    ip: 192.168.1.234
  - zone: kane.mk
    name: pihole1
    ip: 192.168.1.27
  - zone: kane.mk
    name: pihole2
    ip: 192.168.1.60
  - zone: kane.mk
    name: pihole3
    ip: 192.168.1.145
  - zone: kane.mk
    name: pihole4
    ip: 192.168.1.44
  - zone: kane.mk
    name: pihole5
    ip: 192.168.1.3
  - zone: kane.mk
    name: pihole6
    ip: 192.168.1.115
  - zone: kane.mk
    name: playstation5
    ip: 192.168.1.202
  # - zone: kane.mk
  #   name: portainermini
  #   ip: 192.168.1.234
  # - zone: kane.mk
  #   name: proxmini
  #   ip: 192.168.1.10
  - zone: kane.mk
    name: rachiomurdog
    ip: 192.168.107.46
  - zone: kane.mk
    name: router
    ip: 192.168.1.1
  - zone: kane.mk
    name: speedtest
    ip: 192.168.1.66
  - zone: kane.mk
    name: tvalicia
    ip: 192.168.107.67
  - zone: kane.mk
    name: tvlivingroom
    ip: 192.168.107.69
  - zone: kane.mk
    name: tvloft
    ip: 192.168.107.45
  - zone: kane.mk
    name: tvmaster
    ip: 192.168.107.58
  - zone: kane.mk
    name: tvpatio
    ip: 192.168.107.54
  - zone: kane.mk
    name: teckinbugzap
    ip: 192.168.107.57
  - zone: kane.mk
    name: teckinlivingroom
    ip: 192.168.107.59
  - zone: kane.mk
    name: teckinmaster
    ip: 192.168.107.30
  - zone: kane.mk
    name: teckinspare
    ip: 192.168.107.35
  - zone: kane.mk
    name: tivodvroffice
    ip: 192.168.107.47
  - zone: kane.mk
    name: tivolivingroom
    ip: 192.168.107.49
  - zone: kane.mk
    name: tivomaster
    ip: 192.168.107.52
  - zone: kane.mk
    name: tivopatio
    ip: 192.168.107.55
  - zone: kane.mk
    name: usw24poe
    ip: 192.168.1.42
  - zone: kane.mk
    name: uswfmattic
    ip: 192.168.1.175
  - zone: kane.mk
    name: uswfmgarage
    ip: 192.168.1.59
  - zone: kane.mk
    name: uswfmtv
    ip: 192.168.1.186
  - zone: kane.mk
    name: utilserver
    ip: 192.168.1.65
  - zone: kane.mk
    name: vickysipad
    ip: 192.168.1.100
  - zone: kane.mk
    name: vickysphone
    ip: 192.168.1.99
  - zone: kane.mk
    name: yamaha
    ip: 192.168.107.48
  - zone: kane.mk
    name: arris
    ip: 192.168.100.1
  - zone: kane.mk
    name: authentik
    ip: 192.168.1.122
  - zone: kane.mk
    name: coco
    ip: 192.168.1.15
  - zone: kane.mk
    name: kuma
    ip: 192.168.1.152
  - zone: kane.mk
    name: mini
    ip: 192.168.1.10
  - zone: kane.mk
    name: MyQ
    ip: 192.168.107.55     
  - zone: kane.mk
    name: pbs
    ip: 192.168.1.97
  - zone: kane.mk
    name: slzb-06
    ip: 192.168.1.114
  - zone: kane.mk
    name: cyborg
    ip: 192.168.1.191
  - zone: kane.mk
    name: unifi
    ip: 192.168.1.228
  - zone: kane.mk
    name: nvidia
    ip: 192.168.1.9
  - zone: kane.mk
    name: murrypc
    ip: 192.168.1.242
  - zone: kane.mk
    name: nvidia-pve-exporter
    ip: 192.168.1.243
  - zone: kane.mk
    name: pihole2
    ip: 192.168.1.90
  - zone: kane.mk
    name: stargate
    ip: 192.168.1.188
  - zone: kane.mk
    name: dns-primary
    ip: 192.168.1.215
  - zone: kane.mk
    name: dns-secondary
    ip: 192.168.1.219
  - zone: kane.mk
    name: dns-tertiary
    ip: 192.168.1.4
  - zone: kane.mk
    name: kaneserver 
    ip: 192.168.1.20
  - zone: kane.mk 
    name: murdognas 
    ip: 192.168.1.104
  - zone: kane.mk
    name: athena 
    ip: 192.168.1.11
  - zone: kane.mk
    name: apex 
    ip: 192.168.1.12
  - zone: kane.mk
    name: pbs-mini
    ip: 192.168.1.141
  - zone: kane.mk
    name: raptor
    ip: 192.168.1.142