---
records:
  # - zone: 'kaneworld.org'
  #   name: 'coco'
  #   ip: '192.168.1.15'
  # - zone: 'kane.mk'
  #   name: 'coco'
  #   ip: '192.168.1.15'
  # - zone: 'kaneworld.local'
  #   name: 'coco'
  #   ip: '192.168.1.15'
  # - zone: 'kaneworld.local'
  #   name: '@'
  #   ip: '192.168.1.205'
  - zone: kane.mk
		name: kane.mk
    ip: 192.168.1.1
  - zone: kane.mk
		name: kaneworld.org
    ip: 192.168.1.234
  - zone: kane.mk
		name: murdogap.kane.mk
    ip: 192.168.1.170
  - zone: kane.mk
		name: uswfmtv1.kane.mk
    ip: 192.168.107.57
  - zone: kane.mk
		name: uswfmtv2.kane.mk
    ip: 192.168.107.58
  - zone: kane.mk
		name: murpad.kane.mk
    ip: 192.168.1.111
  - zone: kane.mk
		name: adrianasmac.kane.mk
    ip: 192.168.1.197
    exists: false
  - zone: kane.mk
		name: adrianamac.kane.mk
    ip: 192.168.1.187
  - zone: kane.mk
		name: adrianasphone.kane.mk
    ip: 192.168.1.205
  - zone: kane.mk
		name: aliciasipad.kane.mk
    ip: 192.168.1.130
  - zone: kane.mk
		name: aliciasiphone.kane.mk
    ip: 192.168.1.98
  - zone: kane.mk
		name: aliciasmac.kane.mk
    ip: 192.168.1.197
  - zone: kane.mk
		name: aliciaspc.kane.mk
    ip: 192.168.1.217
  - zone: kane.mk
		name: amazonfirecube.kane.mk
    ip: 192.168.107.53
  - zone: kane.mk
		name: amazonfireoffice.kane.mk
    ip: 192.168.107.75
  - zone: kane.mk
		name: amazongarage.kane.mk
    ip: 192.168.107.72
  - zone: kane.mk
		name: amazonhallway.kane.mk
    ip: 192.168.107.44
  - zone: kane.mk
		name: amazonkitchen.kane.mk
    ip: 192.168.107.86
  - zone: kane.mk
		name: amazonmaster.kane.mk
    ip: 192.168.107.32
  - zone: kane.mk
		name: amazonoffice.kane.mk
    ip: 192.168.107.31
  - zone: kane.mk
		name: amazonpatio.kane.mk
    ip: 192.168.107.40
  - zone: kane.mk
		name: amazonplugoffice.kane.mk
    ip: 192.168.107.36
  - zone: kane.mk
		name: applemini.kane.mk
    ip: 192.168.1.226
  - zone: kane.mk
		name: appletv.kane.mk
    ip: 192.168.107.61
  - zone: kane.mk
		name: brendensphone.kane.mk
    ip: 192.168.1.101
  - zone: kane.mk
		name: camerabackyard.kane.mk
    ip: 192.168.1.135
  - zone: kane.mk
		name: cameradoorbell.kane.mk
    ip: 192.168.1.154
  - zone: kane.mk
		name: camerafront.kane.mk
    ip: 192.168.1.70
  - zone: kane.mk
		name: cameragarage.kane.mk
    ip: 192.168.1.64
  - zone: kane.mk
		name: cameragate.kane.mk
    ip: 192.168.1.137
  - zone: kane.mk
		name: camerapatio.kane.mk
    ip: 192.168.1.192
  - zone: kane.mk
		name: fileflow.kane.mk
    ip: 192.168.1.113
  - zone: kane.mk
		name: flumemurdog.kane.mk
    ip: 192.168.107.33
  - zone: kane.mk
		name: goveefense1.kane.mk
    ip: 192.168.107.82
  - zone: kane.mk
		name: goveefense2.kane.mk
    ip: 192.168.107.83
  - zone: kane.mk
		name: goveegazebo.kane.mk
    ip: 192.168.107.85
  - zone: kane.mk
		name: goveespare.kane.mk
    ip: 192.168.107.84
  - zone: kane.mk
		name: hahome.kane.mk
    ip: 192.168.1.209
  - zone: kane.mk
		name: hp8715.kane.mk
    ip: 192.168.1.102
  - zone: kane.mk
		name: homepage.kane.mk
    ip: 192.168.1.234
  - zone: kane.mk
		name: jfmini.kane.mk
    ip: 192.168.1.230
    exists: false
  - zone: kane.mk
		name: pihole1.kane.mk
    ip: 192.168.1.27
  - zone: kane.mk
		name: pihole2.kane.mk
    ip: 192.168.1.60
    exists: false
  - zone: kane.mk
		name: pihole3.kane.mk
    ip: 192.168.1.145
  - zone: kane.mk
		name: pihole4.kane.mk
    ip: 192.168.1.44
    exists: false
  - zone: kane.mk
		name: pihole5.kane.mk
    ip: 192.168.1.3
  - zone: kane.mk
		name: pihole6.kane.mk
    ip: 192.168.1.115
  - zone: kane.mk
		name: playstation5.kane.mk
    ip: 192.168.1.202
  - zone: kane.mk
		name: portainermini.kane.mk
    ip: 192.168.1.234
  - zone: kane.mk
		name: proxmini.kane.mk
    ip: 192.168.1.10
  - zone: kane.mk
		name: rachiomurdog.kane.mk
    ip: 192.168.107.46
  - zone: kane.mk
		name: router.kane.mk
    ip: 192.168.1.1
  - zone: kane.mk
		name: speedtest.kane.mk
    ip: 192.168.1.66
  - zone: kane.mk
		name: tvalicia.kane.mk
    ip: 192.168.107.67
  - zone: kane.mk
		name: tvlivingroom.kane.mk
    ip: 192.168.107.69
  - zone: kane.mk
		name: tvloft.kane.mk
    ip: 192.168.107.45
  - zone: kane.mk
		name: tvmaster.kane.mk
    ip: 192.168.107.58
  - zone: kane.mk
		name: tvpatio.kane.mk
    ip: 192.168.107.54
  - zone: kane.mk
		name: teckinbugzap.kane.mk
    ip: 192.168.107.57
  - zone: kane.mk
		name: teckinlivingroom.kane.mk
    ip: 192.168.107.59
  - zone: kane.mk
		name: teckinmaster.kane.mk
    ip: 192.168.107.30
  - zone: kane.mk
		name: teckinspare.kane.mk
    ip: 192.168.107.35
  - zone: kane.mk
		name: tivodvroffice.kane.mk
    ip: 192.168.107.47
    exists: false
  - zone: kane.mk
		name: tivolivingroom.kane.mk
    ip: 192.168.107.49
    exists: false
  - zone: kane.mk
		name: tivomaster.kane.mk
    ip: 192.168.107.52
    exists: false
  - zone: kane.mk
		name: tivopatio.kane.mk
    ip: 192.168.107.55
    exists: false
  - zone: kane.mk
		name: usw24poe.kane.mk
    ip: 192.168.1.42
  - zone: kane.mk
		name: uswfmattic.kane.mk
    ip: 192.168.1.175
  - zone: kane.mk
		name: uswfmgarage.kane.mk
    ip: 192.168.1.59
  - zone: kane.mk
		name: uswfmtv.kane.mk
    ip: 192.168.1.186
  - zone: kane.mk
		name: utilserver.kane.mk
    ip: 192.168.1.65
  - zone: kane.mk
		name: vickysipad.kane.mk
    ip: 192.168.1.100
  - zone: kane.mk
		name: vickysphone.kane.mk
    ip: 192.168.1.99
  - zone: kane.mk
		name: yamaha.kane.mk
    ip: 192.168.107.48
  - zone: kane.mk
		name: arris.kane.mk
    ip: 192.168.100.1
  - zone: kane.mk
		name: authentik.kane.mk
    ip: 192.168.1.122
  - zone: kane.mk
		name: coco.kane.mk
    ip: 192.168.1.15
  - zone: kane.mk
		name: kuma.kane.mk
    ip: 192.168.1.152
  - zone: kane.mk
		name: mini.kane.mk
    ip: 192.168.1.10
  - zone: kane.mk
		name: MyQ.kane.mk
    ip: 192.168.107.55     
  - zone: kane.mk
		name: pbs.kane.mk
    ip: 192.168.1.97
  - zone: kane.mk
		name: slzb-06.kane.mk
    ip: 192.168.1.114
  - zone: kane.mk
		name: cyborg.kane.mk
    ip: 192.168.1.191
  - zone: kane.mk
		name: rke2-prod-1.kane.mk
    ip: 192.168.1.239
  - zone: kane.mk
		name: rke2-prod-2.kane.mk
    ip: 192.168.1.236
  - zone: kane.mk
		name: rke2-prod-3.kane.mk
    ip: 192.168.1.169
  - zone: kane.mk
		name: rke2-prod-4.kane.mk
    ip: 192.168.1.218
  - zone: kane.mk
		name: rke2-prod-5.kane.mk
    ip: 192.168.1.227
  - zone: kane.mk
		name: rke2-prod-6.kane.mk
    ip: 192.168.1.173
  - zone: kane.mk
		name: rke2-prod-7.kane.mk
    ip: 192.168.1.208
  - zone: kane.mk
		name: longhorn-prod-1.kane.mk
    ip: 192.168.1.41
  - zone: kane.mk
		name: longhorn-prod-2.kane.mk
    ip: 192.168.1.197
  - zone: kane.mk
		name: longhorn-prod-3.kane.mk
    ip: 192.168.1.216
  - zone: kane.mk
		name: longhorn-prod-4.kane.mk
    ip: 192.168.1.213
  - zone: kane.mk
		name: longhorn-prod-5.kane.mk
    ip: 192.168.1.211
    exists: false
  - zone: kane.mk
		name: kube-vip.kane.mk
    ip: 192.168.1.25
  - zone: kane.mk
		name: traefik4.kane.mk
    ip: 192.168.1.26
  - zone: kane.mk
		name: unifi.kane.mk
    ip: 192.168.1.228
  - zone: kane.mk
		name: nvidia.kane.mk
    ip: 192.168.1.9
  - zone: kane.mk
		name: murrypc.kane.mk
    ip: 192.168.1.242
  - zone: kane.mk
		name: nvidia-pve-exporter.kane.mk
    ip: 192.168.1.243
  - zone: kane.mk
		name: pihole2.kane.mk
    ip: 192.168.1.90
  - zone: kane.mk
		name: stargate.kane.mk
    ip: 192.168.1.188
  - zone: kane.mk
		name: jellyfin.kane.mk
    ip: 192.168.1.20
  - zone: kane.mk
		name: tinymedia.kane.mk 
    ip: 192.168.1.20 
  - zone: kane.mk
		name: filebot.kane.mk 
    ip: 192.168.1.20 
