---
- name: "Install Checkmk agent on all hosts"
  #hosts: "{{ my_hosts | d([]) }}"
  hosts: " {{ scriptinventory }}"
  roles:
    - checkmk.general.agent
  vars:
    checkmk_agent_version: "{{ checkmk_agent_version }}"
    checkmk_agent_server: "{{ site }}"
    checkmk_agent_server_protocol: https
    checkmk_agent_site: "{{ site }}"
    checkmk_agent_auto_activate: true
    checkmk_agent_tls: "true"  # NOTE: Register Agent to enable TLS
    checkmk_agent_user: "{{ automation_user }}"
    checkmk_agent_pass: "{{ automation_secret }}"
    checkmk_agent_host_name: "{{ ansible_hostname }}"  # NOTE: Required to replace FQDN with hostname only
  vars_files:
    - var/checkmk_secrets.yaml