---
- name: "Install Checkmk agent on all hosts"
  #hosts: "{{ my_hosts | d([]) }}"
  hosts: " {{ scriptinventory }}"
  roles:
    - checkmk.general.agent
  vars:
    checkmk_agent_version: 2.4.0p8
    #checkmk_agent_server: "cyborg.kane.mk"
    checkmk_agent_server: checkmk.local.kaneworld.org
    checkmk_agent_registration_server: checkmk.local.kaneworld.org:8005
    #checkmk_agent_edition: " {{ checkmk_edition }}"
    checkmk_agent_server_protocol: https
    checkmk_agent_add_host: true
    checkmk_agent_discover: true
    checkmk_agent_no_log: false
    checkmk_agent_site: KaneCo
    checkmk_agent_auto_activate: true
    checkmk_agent_legacy_mode: false
    checkmk_agent_force_foreign_changes: true
    checkmk_agent_disable_port_check: true
    checkmk_agent_mode: pull
    checkmk_agent_tls: true  # NOTE: Register Agent to enable TLS
    checkmk_agent_user: murrykane
    checkmk_agent_pass: i4eKFBOODdZ&KNuS
    checkmk_agent_host_name: "{{ ansible_hostname }}"  # NOTE: Required to replace FQDN with hostname only
    checkmk_agent_ip_address: "{{ ansible_default_ipv4.address }}"   #NOTE: needed IP address for checkmk to work
  vars_files:
    - /vars/checkmk_secrets.yml