---
- name: "Activate Checkmk changes"
  hosts: localhost
  gather_facts: false
  # vars_files:
  #   - vars/checkmk_secrets.yaml
  # vars:
  #   server_url: "checkmk.home.arpa"
  #   site: "cmk"

  collections:
    - checkmk.general

  tasks:

    - name: include vars 
      ansible.builtin.include_vars: vars/checkmk_secrets.yml

    - name: "Start activation on a specific site"
      checkmk.general.activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        sites:
          - "{{ site }}"