- hosts: all
  gather_facts: yes
  tasks:
    - name: Get whoami information for Windows
      win_whoami:
      when: ansible_facts['os_family'] == 'Windows'
    - name: Get whoami information for Linux
      ansible.buildin.debug:
        msg: "{{ lookup('env', 'USER') }}"
      when: ansible_facts['os_family'] != 'Windows'