---
- name: Read shared public key (on localhost)
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read shared public key from files/id_rsa.pub
      slurp:
        src: "files/semaphore_id.pub"
      register: pubkey_contents

- name: Install core packages for virtual machines
  hosts: "{{ scriptinventory }}"
  become: true
  vars:
    users:
      - semaphore
      - murry
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - nfs-common
          - qemu-guest-agent
        update_cache: true

    - name: Create group
      group:
        name: "sudo"
        state: present

    - name: Create users
      user:
        name: "{{ item }}"
        create_home: true
        append: true
        state: present
        generate_ssh_key: true
        shell: /bin/bash
        groups: admin, sudo
      loop: "{{ users }}"

    - name: Ensure .ssh directory exists for each user
      file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Append shared public key to authorized_keys
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/.ssh/authorized_keys"
        line: "{{ hostvars['localhost']['pubkey_contents'].content | b64decode | trim }}"
        create: yes
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0600'
      loop: "{{ users }}"




