---
- name: Install core packages for virtual machines
  #hosts: "{{ my_hosts | d([]) }}"
  hosts: "{{ scriptinventory }}"
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - nfs-common
          - qemu-guest-agent
        update_cache: true

    # - name: Start guest qemu-guest-agent
    #   ansible.builtin.service:
    #     name: qemu-guest-agent
    #     state: started
    #     enabled: true

    - name: Create group
      group:
        name: "{{ admin_group }}"
        state: present

    - name: Create Users Task
      user:
        name: "{{ item }}"
        create_home: true
        append: true
        state: present
        generate_ssh_key: true
        shell: /bin/bash
        groups: admin, sudo
      loop:
        - semaphore
        - murry

    # - name: Add User Semaphore
    #   ansible.builtin.user:
    #     name: semaphore
    #     shell: /bin/bash
    #     create_home: yes
    #     group: admin, sudo
    #   become: yes

    # - name: Add User Murry
    #   ansible.builtin.user:
    #     name: murry
    #     shell: /bin/bash
    #     create_home: yes
    #     group: admin, sudo
    #   become: yes
