---
#- hosts: ubuntu:prox
- hosts: ubuntu
  become: yes
  tasks:
  - name: make sure net-tools are installed on all nodes
    apt:
      name: net-tools
      state: present
  - name: make sure apache2-utils are installed on all nodes
    apt:
      name: apache2-utils
      state: present
    when:
      - inventory_hostname != 'proxmini.kane.mk'
