---
- name: Ensure NTP is installed and time is synchronized
  hosts: ubuntu:prox
  become: yes

  tasks:

    - name: Install chrony (NTP client)
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Enable and start chrony service
      ansible.builtin.service:
        name: chrony
        enabled: yes
        state: started

    - name: Configure chrony with custom NTP servers
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart chrony

    - name: Force time sync now
      ansible.builtin.command: chronyc makestep
      when: ansible_facts['distribution'] != "Debian"

  handlers:
    - name: Restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted