---
- name: Test connectivity to hosts
  #hosts: all:!windows
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ping the host for linux
      ansible.builtin.ping:
      when: ansible_facts['os_family'] != 'Windows'

    - name: Ping the host for Windows
      ansible.windows.win_ping:
      when: ansible_facts['os_family'] == 'Windows'