---
# docker ps -a | awk -F' ' '{print $NF}' | grep -v NAMES
- hosts: 'mkserver.kane.mk'
  become: yes
  tasks:
    - name: Prune Docker images
      docker_image_prune:
        dangling: yes
        # filters:
        #   label:
        #     - my_custom_label  # Optionally, filter by a specific label
      register: prune_output

    - name: Show pruned images output
      debug:
        var: prune_output
