---
# docker ps -a | awk -F' ' '{print $NF}' | grep -v NAMES
- hosts: 'mkserver.kane.mk'
  become: yes
  tasks:
    - name: Prune Docker images
      docker_prune:
        images: false
        containers: false
        networks: false
        volumes: true
        images_filters:
          dangling: true
      register: prune_output

    - name: Show pruned images output
      debug:
        var: prune_output
