---
- name: Pull repos from GitHub to cyborg
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/repo_targets.yml

  tasks:

    # removing GIT download as I don't source control .env files and cf_token and still need these on other servers.....
    # - name: Clone or update repos on cyborg
    #   ansible.builtin.git:
    #     repo: "git@github.com:murrykane/{{ item.name }}.git"
    #     dest: "{{ repo_base_path }}/{{ item.name }}"
    #     update: true
    #     version: main
    #     force: true
    #     accept_hostkey: true
    #     key_file: ~/.ssh/id_rsa
    #   loop: "{{ repos }}"

    - name: rsync each repo from NAS to local
      ansible.builtin.synchronize:
        src: "root@kaneserver.kane.mk:{{ unraid_base_path }}/{{ item.name }}/"
        dest: "{{ repo_base_path }}/{{ item.name }}"
        mode: pull
        group: false
        owner: false
        perms: false
      loop: "{{ repos }}"

    # this group does not exist inside the semaphore container, skipping since I ignore group/owner above....
    # - name: Set permissions on Repos on cyborg
    #   ansible.builtin.file:
    #     path: "{{ repo_base_path }}"
    #     owner: semaphore
    #     group: repogroup
    #     mode: '0755'
    #     recurse: yes


- name: Setup repogroup on target servers
  hosts: repo_servers
  gather_facts: false
  vars_files:
    - vars/repo_targets.yml

  tasks:
    - name: Ensure repogroup exists
      ansible.builtin.group:
        name: repogroup
        gid: 1004
        state: present
      become: true

    - name: Add users to repogroup
      ansible.builtin.user:
        name: "{{ item }}"
        groups: repogroup
        append: true
      loop:
        - murry
        - semaphore
      become: true

    - name: Ensure dest base directory exists with correct ownership
      ansible.builtin.file:
        path: "{{ dest_base_path }}"
        state: directory
        #owner: root
        owner: semaphore
        group: repogroup
        mode: '2775'
      become: true

- name: Push code repositories to target servers
  hosts: repo_servers
  gather_facts: false
  vars_files:
    - vars/repo_targets.yml

  tasks:
    - name: Ensure destination base directory exists
      ansible.builtin.file:
        path: "{{ dest_base_path }}"
        state: directory
        mode: '0755'
      become: true

    - name: Sync repos to servers that are listed as targets
      ansible.builtin.synchronize:
        src: "{{ item.src }}/"
        dest: "{{ dest_base_path }}/{{ item.name }}"
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude=.git"
      loop: "{{ repos | selectattr('targets', 'contains', inventory_hostname) | list }}"
      loop_control:
        label: "{{ item.name }} → {{ inventory_hostname }}"
      become: true