---
- name: Send discord Message
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Send a message to the Discord channel with specific username and avatar
      community.general.discord:
        webhook_id: "{{ webhook_id }}"
        webhook_token: "{{ webhook_token }}"
        content: "This is a message from ansible, murry is the man!"
        username: Ansible
        #avatar_url: "https://docs.ansible.com/ansible/latest/_static/images/Ansible-Mark-RGB_Black.png"
        avatar_url: "https://pantheon.tech/wp-content/uploads/2019/04/ansible.png"
