---
- hosts: ubuntu
  become: yes
  tasks:
  - name: make sure ACL's are in place for Docker and Telegraf
    ansible.builtin.systemd:
      name: set-docker-acl
      state: restart
    when:
      - inventory_hostname == 'mkserver.kane.mk'
