---
#- hosts: docker:qnap
- hosts: docker
  become: yes
  tasks:
  - name: Start all containers for Docker
    block:
      # - name: Get list of all containers
      #   #shell: docker ps -aq
      #   shell: "{{ docker_bin | default('docker') }} ps -aq"
      #   register: container_list

      - name: Get list of all containers
        shell: /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker ps -aq
        register: container_list
        when: inventory_hostname in groups['qnap']

      - name: Get list of all containers
        shell: docker ps -aq
        register: container_list
        when: inventory_hostname not in groups['qnap']

      - name: Start containers
        docker_container:
          name: "{{ item }}"
          state: started
          comparisons:
            '*': ignore  # by default, ignore *all* options (including image)
        loop: "{{ container_list.stdout_lines }}"
      
      #- name: Start containers one
      #  docker_container:
      #    name: 8af569599399
      #    state: started
      #    comparisons:
      #      '*': ignore  # by default, ignore *all* options (including image)
      
    # when:
    #   - inventory_hostname == 'mkserver.kane.mk' or inventory_hostname == 'utilserver.kane.mk' or inventory_hostname == "cyborg.kane.mk" or inventory_hostname == 'minidocker.kane.mk'
