---
- hosts: ubuntu
  become: yes
  vars:
    container_home: '/home/murry/containers/'
  tasks:
  - name: Update all containers for Docker
    block:
      - name: Get list of all docker-compose containers
        shell: find /home/murry/containers -name docker-compose.yml -print
        register: container_list

      - name: List found containers docker compose files 
        debug: container_list
  
      # - name: Start containers
      #   docker_container:
      #     name: "{{ item }}"
      #     state: started
      #     comparisons:
      #       '*': ignore  # by default, ignore *all* options (including image)
      #   loop: "{{ container_list.stdout_lines }}"
      
      
    when:
      - inventory_hostname == 'mkserver.kane.mk'