---
- hosts: ubuntu
  become: yes
  vars:
    container_home: '/home/murry/containers/'
  tasks:
  - name: Update all containers for Docker
    block:
      - name: Get list of all docker-compose containers
        shell: find "{{ container_home }}" -name docker-compose.yml -print
        register: container_list

      - name: List found containers docker compose files 
        ansible.builtin.debug: 
          var: container_list

      - name: Iterate over Docker Compose directories
        ansible.builtin.find:
          paths: "{{ container_home }}"
          file_type: directory
        register: compose_dirs

      - name: List found containers docker compose file directories
        ansible.builtin.debug: 
          var: compose_dirs

      - name: List containers
        ansible.builtin.debug:
          var: "Directory: {{ item.path }}"
        loop: "{{ compose_dirs.files }}"

      # - name: Update containers
      #   docker_compose:
      #     project_src: "{{ item }}"
      #     pull: yes
      #     recreate: always
      #   loop: "{{ compose_dirs.files.path }}"
      
      
    when:
      - inventory_hostname == 'mkserver.kane.mk'